import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import localFont from "next/font/local";

const vazir = localFont({
    src: "./Vazir.woff2",
    display: "swap",
});

export const metadata = {
    title: "Quiz App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, about }) {
    return (
        <html lang="fa-IR" dir="rtl" className={vazir.className}>
            <body>
                {children}
                {about}
            </body>
        </html>
    );
}
